# Generated by Django 5.2.4 on 2025-11-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_produit', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('stock_produit', models.CharField(max_length=180)),
                ('prix_produit', models.DecimalField(decimal_places=0, max_digits=8)),
                ('image_produit', models.ImageField(blank=True, null=True, upload_to='photos')),
            ],
        ),
    ]
