# Generated by Django 5.2.4 on 2025-11-23 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='stock_produit',
            field=models.IntegerField(),
        ),
    ]
