# Generated by Django 5.2.4 on 2025-11-30 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0003_formulairecontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_article', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('stock_article', models.IntegerField()),
                ('prix_article', models.DecimalField(decimal_places=0, max_digits=8)),
                ('image_article', models.ImageField(blank=True, null=True, upload_to='photos')),
            ],
        ),
    ]
