# Generated by Django 5.2.4 on 2025-12-09 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0004_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='prix_article',
        ),
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='article',
            name='stock_article',
        ),
    ]
