# Generated by Django 5.2.4 on 2025-12-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0005_remove_article_prix_article_remove_article_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table_maillot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_maillot', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('prix_maillot', models.DecimalField(decimal_places=0, max_digits=8)),
                ('image_maillot', models.ImageField(blank=True, null=True, upload_to='photos')),
            ],
        ),
    ]
