# Generated by Django 5.2.4 on 2025-12-27 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0006_table_maillot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_article', models.CharField(max_length=180)),
                ('image_article', models.ImageField(blank=True, null=True, upload_to='photos')),
            ],
        ),
    ]
