# Generated by Django 5.2.4 on 2025-12-29 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0007_article1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article1',
        ),
        migrations.DeleteModel(
            name='Table_maillot',
        ),
    ]
